[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM17
monitor_port = COM17

; Configurazione Flash (Il tuo modulo ha 4MB di flash, ma di default il DevKitC si aspetta 8MB)
board_upload.flash_size = 4MB
board_build.partitions = default.csv

; Abilita l'output seriale sulla porta USB nativa (comune per ESP32-S3)
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D WS_MAX_QUEUED_MESSAGES=8

lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    wollewald/ADS1220_WE @ ^1.0.11
