[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM17
monitor_port = COM17
board_upload.flash_size = 4MB
board_build.partitions = default.csv

extra_scripts = pre:../tools/gen_webui.py

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D WS_MAX_QUEUED_MESSAGES=8
    -D CORE_DEBUG_LEVEL=0
    -I../shared

lib_deps =
    wollewald/ADS1220_WE @ ^1.0.11
    mathieucarbou/ESPAsyncWebServer @ ^3.3.17
